name: Execute Ploomber pipeline

on:
  schedule:
    - cron: '0 * * * *' # Run at the start of every hour

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Poetry using pip
      run: |
        python -m pip install poetry

    - name: Install dependencies using Poetry
      run: |
        poetry install

    - name: Run Ploomber pipeline to fetch and push data to MotherDuck
      env:
        MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
        API_KEY: ${{ secrets.API_KEY }} 
      run: |
        poetry run ploomber build